[package]
name = "music-chore"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
serde_json = "1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
lofty = "0.22.4"

[dev-dependencies]
tempfile = "3"
