name: Rust Build and Publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
            # target: x86_64-unknown-linux-gnu
          # - os: windows-latest
            # target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v5

      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2

      - name: Install target
        run: rustup target add ${{ matrix.target }}
      
      - name: Build
        run: cargo build
        
      - name: Run tests
        run: cargo test --verbose
  
      - name: Build Release
        run: cargo build --release --target ${{ matrix.target }}
        
      - name: Package artifact
        run: |
          mkdir dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/musicctl.exe dist/
          else
            cp target/${{ matrix.target }}/release/musicctl dist/
          fi
          tar -czf musicctl-${{ matrix.target }}.tar.gz -C dist .

      - name: Generate install.sh
        run: |
          cat << 'EOF' > dist/install.sh
          #!/usr/bin/env bash
          set -e
          TOOL_NAME="musicctl"
          REPO="${GITHUB_REPOSITORY}"

          OS="$(uname | tr '[:upper:]' '[:lower:]')"
          ARCH="$(uname -m)"

          if [ "$OS" == "darwin" ]; then
              if [ "$ARCH" == "arm64" ]; then
                  TARGET="aarch64-apple-darwin"
              else
                  TARGET="x86_64-apple-darwin"
              fi
          else
              echo "Currently only macOS is supported"
              exit 1
          fi

          URL="https://github.com/$REPO/releases/latest/download/$TOOL_NAME-$TARGET.tar.gz"
          echo "Downloading $URL..."
          curl -LO "$URL"
          tar -xzf "$TOOL_NAME-$TARGET.tar.gz"
          chmod +x "$TOOL_NAME"
          sudo mv "$TOOL_NAME" /usr/local/bin/
          xattr -dr com.apple.quarantine /usr/local/bin/$TOOL_NAME || true
          echo "$TOOL_NAME installed successfully!"
          EOF

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: musicctl-${{ matrix.target }}
          path: |
            dist/musicctl-${{ matrix.target }}.tar.gz
            dist/install.sh
  release:
      name: Create GitHub Release
      needs: build
      runs-on: ubuntu-latest
  
      steps:
        - name: Download all artifacts
          uses: actions/download-artifact@v4
          with:
            path: artifacts
  
        - name: Create Release
          uses: softprops/action-gh-release@v2
          with:
            files: artifacts/**/*
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
